nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 3AE94518-17A9-486F-BAD3-D5142C1576DD
    npmRegistryServer: 'https://npm.fontawesome.com/'
  uis:
    npmRegistryServer: 'https://proget.az.sis.jhu.edu/npm/uis/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
